/************************************************************
 *  Common.h    :   common include things                   *
 *  Version     :   1.0										*
 *  Copyright   :   THU NCC									*
 *															*
 *  ------- EditLog -------									*
 *  Apr.12,2002   :  Created by windbell9@sina.com			*
 *															*
 ************************************************************/

#ifndef _COMMON_H_
#define _COMMON_H_

//#include <math.h>
//#include "gl/gl.h"
//#include "gl/glu.h"
//#include "gl/glaux.h"

#define DOUBLE_EPS 1e-16
// double zero eps
#define	EQUALZERO(x)	(fabs((x)) < DOUBLE_EPS)	

#endif
