/************************************************************
 *  Common.cpp  :   common include things                   *
 *  Version     :   1.0										*
 *  Copyright   :   THU NCC									*
 *															*
 *  ------- EditLog -------									*
 *  Apr.12,2002   :  Created by windbell9@sina.com			*
 *															*
 ************************************************************/

#include "common.h"

const double COMMON::_double_eps = 1e-16;
const int	 COMMON::NONE = 0;
const int	 COMMON::TRIANGLE = 3;